name: fabulousgirl
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4

  # Bloc
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  
  # Custom Repository
  user_repository: 
    path: packages/user_repository


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
